apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cloud-storage
  description: Cloud Storage bucket with versioning and lifecycle policies
  tags:
    - gcp
    - storage
  annotations:
    github.com/project-slug: spotify-portal-public-demo/central-iac-repo
spec:
  type: storage
  lifecycle: production
  owner: group:infraops
